import { chromium } from "playwright-core";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome", args:["--no-sandbox"]});
const ctx = await b.newContext({ viewport: { width: 390, height: 900 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
const p = await ctx.newPage();
p.on("pageerror", e => console.log("[pageerror]", String(e).slice(0,300)));
await p.goto("http://localhost:3000/next/new", { waitUntil: "domcontentloaded", timeout: 60000 });
await p.waitForTimeout(3500);
await p.screenshot({ path: "/tmp/shots/draft.png" });
console.log("h2:", await p.$$eval("h2", n=>n.map(x=>x.textContent)));
await b.close();
