import { chromium } from "playwright-core";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome", args:["--no-sandbox"]});
const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
const p = await ctx.newPage();
p.on("pageerror", e => console.log("[pageerror]", String(e).slice(0,250)));
await p.addInitScript(() => localStorage.setItem("ayato-island-arrived", "1"));
const B = "https://live-streaming-d3cac.web.app";
await p.goto(B + "/", { waitUntil: "domcontentloaded", timeout: 90000 });
await p.waitForTimeout(6000);
console.log("view:", await p.getAttribute(".stage","data-view"), "residents:", await p.$$eval(".stage-svg image", n => n.filter(i=>i.getAttribute("href")?.includes("googleusercontent")).length), "calls:", await p.$$eval(".who-call", n=>n.length));
await p.screenshot({ path: "/tmp/shots/p-close.png" });
await p.evaluate(() => window.scrollTo(0, 760)); await p.waitForTimeout(700);
await p.screenshot({ path: "/tmp/shots/p-next.png" });
await p.goto(B + "/nordic", { waitUntil: "domcontentloaded", timeout: 90000 });
await p.waitForTimeout(3000);
await p.screenshot({ path: "/tmp/shots/p-nordic.png" });
await p.goto(B + "/nordic/poland", { waitUntil: "domcontentloaded", timeout: 90000 });
await p.waitForTimeout(3500);
await p.evaluate(() => window.scrollTo(0, 1400)); await p.waitForTimeout(1500);
await p.screenshot({ path: "/tmp/shots/p-poland.png" });
await b.close();
